spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://120.76.72.31:3306/mydb?useSSL=false'
    username: ****
    password: ***********
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0